# Generated by Django 3.2.2 on 2024-03-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habr_Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('name_author', models.CharField(max_length=1000)),
                ('url_author', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Habs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hab', models.CharField(max_length=1000)),
                ('title_article', models.CharField(max_length=1000)),
            ],
        ),
    ]
